### ISSUE TITLE
Commandlist dropdown

### ISSUE THREAD

**Issue by TheCell** [bschug/poedit#13]
would be nice to see a dropdown selection (or a suggestion mode while write) of available commands. Or maybe a Dropdown of patterns to choose from for easy building. You could for example have a List with already implemented premade patterns. Like show items with chromatic links (RGB linked) and so on. Would be like an easy tape together mode.

**Comment by bschug** [comment]
I'm not exactly sure what you mean. There is already an autocompletion that shows suggestions as you type, for all keywords. Doesn't it work for you? You can show the complete list of all keywords by pressing Ctrl+Space on an empty line.

**Comment by TheCell** [comment]
Something like a dropdown Menu with premade show/hide blocks. Like Show chromatic items. If you select that it automatically adds a block to the script, would help to easily stick together a script for absolute script noobies:
Show
    SocketGroup RGB
    SetBorderColor 31 203 233

Hm well as I continue to elaborate on this it shows that it is not a lot of value since you can filter a LOT with very few commands. Noobs will probably copy pasterino scripts as a whole anyway.

Guess you can close this suggestion nevermind :)

**Comment by bschug** [comment]
Yeah, there are better tools for people who just want to click scripts together from building blocks without understanding the script syntax. That was never the intention of this tool.
